import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AgentInfoLayout({
  children,
  agent,
  listings,
}: Readonly<{
  children: React.ReactNode;
  agent: React.ReactNode;
  listings: React.ReactNode;
}>) {
  return (
     <div className="agentInfoContainer">
      {children}
      {agent}
      {listings}
     </div>
   
  );
}
