
import '@styles'
import AgentDashboardNav from "@components/AgentDashboardNav";
import Footer from "@components/Footer";
import User from '@utils/user'
import Provider from '@utils/sessionProvider'
import ReactQueryProvider from '@utils/ReactQueryProvider';
import Notification from '@lib/Notification'
import Backdrop from '@lib/Backdrop'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AgentDashboardLayout({agent,listings}){ 
    return (
    <html>

   <body>
    <Provider>
      <User>
        <Backdrop>
  <AgentDashboardNav/>
     <div className="agentDashboardContainer">
      {agent}
      {listings}
     </div>
     <Footer className={'hide'}/>
          </Backdrop>
      </User>
    </Provider>
  
     </body>
    </html>
  );
}
